### ISSUE TITLE
fails on Ubuntu-18.04

### ISSUE THREAD

**Issue by davekimble2** [shackra/pyxss#1]
Ubuntu-18.04, python-3.6.7, wxPython-4.0.1

setup.py Line 49+50: 
    if print_config: 
        print("Checking for SWIG... ", end= ' ')   
                                                             ^
Syntax error

Seems OK to me, but I removed second parameter, and Installation seemed to go OK, but on execution of script
import xss
ModuleNotFoundError: No module named 'xss'

Also tried "Xss", "XSS and "PyXSS"
**How do you discover which modules are available to be imported?
How do you discover which methods are present on a particular module?**

**Comment by davekimble2** [comment]
^ should align with "="

**Comment by shackra** [comment]
Hi @davekimble2 

I'm not actively maintaining this package, so sadly I cannot lend you a hand about this bug you are reporting
